name: Build

on:
  push:
    branches: [main, stable]
    tags:
      - '!v*'
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install modules.
        run: yarn install --frozen-lockfile
      - name: Build artifacts.
        run: yarn dist:win portable
      - name: Upload EXE.
        uses: actions/upload-artifact@v3
        with:
          name: win-portable
          path: dist/Heroic*.exe
          retention-days: 14
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install --no-install-recommends -y snapcraft
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install modules.
        run: yarn install --frozen-lockfile
      - name: Upload Snap to Edge Channel.
        run: yarn dist:linux snap --publish=always
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_ID_EDGE }}
      - name: Build artifacts.
        run: yarn dist:linux appimage --publish=never
      - name: Upload AppImage.
        uses: actions/upload-artifact@v3
        with:
          name: linux-appimage
          path: dist/Heroic-*.AppImage
          retention-days: 14
  build_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install modules.
        run: yarn install --frozen-lockfile
      - name: Build artifacts.
        run: yarn dist:mac --x64 --arm64 --publish=never
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
      - name: Upload x64.
        uses: actions/upload-artifact@v3
        with:
          name: mac-x64
          path: dist/Heroic*x64.dmg
          retention-days: 14
      - name: Upload ARM64.
        uses: actions/upload-artifact@v3
        with:
          name: mac-arm64
          path: dist/Heroic*arm64.dmg
          retention-days: 14
