name: Build Linux

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Test Files'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: install dependencies 
        run: sudo apt install snapcraft -y
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules.
        run: yarn
      - name: Upload Snap to Edge Channel.
        run: yarn dist:linux snap --publish=always
        env:
          PUBLISH_FOR_PULL_REQUEST: true
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_ID_EDGE }}
      - name: Build artifacts.
        run: yarn dist:linux appimage --publish=never
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Upload AppImage.
        uses: actions/upload-artifact@v3
        with:
          name: linux-appimage
          path: dist/Heroic-*.AppImage
          retention-days: 14
